CREATE DATABASE IF NOT EXISTS usermgt;
USE usermgt;
CREATE TABLE IF NOT EXISTS `user` (
   `id` INT NOT NULL AUTO_INCREMENT,
   `first_name` VARCHAR(45) NOT NULL,
   `last_name` VARCHAR(45) NOT NULL,
   `email` VARCHAR(45) NOT NULL,
   `phone` VARCHAR(45) NOT NULL,
   `comments` TEXT NOT NULL,
   `status` VARCHAR(10) NOT NULL DEFAULT 'active',
   PRIMARY KEY (`id`)
) ENGINE=InnoDB;

/**INSERT INTO `user` 
(`first_name`, `last_name`, `email`, `phone`, `comments`, `status`)
VALUES
('Amanda', 'Nunes', 'anunes@ufc.com', '012345 678910', 'I Love VPS', 'active');
**/
INSERT INTO `user` 
(`first_name`, `last_name`, `email`, `phone`, `comments`, `status`)
VALUES
('Alexander', 'Volkanovski', 'avolkanovski@ufc.com', '012345 678910', 'Training harder than ever for the next championship fight, I’m all in.', 'active'),
('Khabib', 'Nurmagomedov', 'knurmagomedov@ufc.com', '012345 678910', 'Retirement mode, but still watching the sport I love with passion and care.', 'disabled'),
('Kamaru', 'Usman', 'kusman@ufc.com', '012345 678910', 'The road to the title never ends; I will be back to claim what’s mine.', 'active'),
('Israel', 'Adesanya', 'iadesanya@ufc.com', '012345 678910', 'Still chasing greatness, always evolving and getting better with every fight.', 'active'),
('Henry', 'Cejudo', 'hcejudo@ufc.com', '012345 678910', 'Aiming for a third belt and becoming the greatest combat athlete of all time.', 'disabled'),
('Valentina', 'Shevchenko', 'vshevchenko@ufc.com', '012345 678910', 'Champion mindset always, focused on maintaining my legacy in MMA and beyond.', 'active'),
('Tyron', 'Woodley', 'twoodley@ufc.com', '012345 678910', 'Back on track for the title, no one is stopping me from getting what I deserve.', 'disabled'),
('Rose', 'Namajunas', 'rnamajunas@ufc.com', '012345 678910', 'Focused on improving every day, determined to reclaim my place at the top.', 'active'),
('Tony', 'Ferguson', 'tferguson@ufc.com', '012345 678910', 'Chaos never stops, always ready for the fight, my mentality is unbeatable.', 'disabled'),
('Jorge', 'Masvidal', 'jmasvidal@ufc.com', '012345 678910', 'Street Jesus is back, ready to take on anyone and prove I am the best in the world.', 'active'),
('Nate', 'Diaz', 'ndiaz@ufc.com', '012345 678910', 'You know how I do – ready to fight anytime, anywhere, for the fans and myself.', 'disabled'),
('Conor', 'McGregor', 'cmcGregor@ufc.com', '012345 678910', 'The king is back! Ready to reclaim my throne and silence the critics once and for all.', 'active'),
('Cris', 'Cyborg', 'ccyborg@ufc.com', '012345 678910', 'Always on top, always grinding, always getting stronger for the next challenge.', 'active'),
('Tecia', 'Torres', 'ttorres@ufc.com', '012345 678910', 'Focused on getting back to the top, never backing down from any challenge that comes my way.', 'disabled'),
('Ronda', 'Rousey', 'rrousey@ufc.com', '012345 678910', 'I’m a fighter, always will be, and I’m coming back to prove my worth once again.', 'active'),
('Holly', 'Holm', 'hholm@ufc.com', '012345 678910', 'The hunt for another title begins; I’m ready to show the world I can be a champion again.', 'disabled'),
('Amanda', 'Nunes', 'anunes01@ufc.com', '012345 678911', 'Training hard for the next fight, never losing focus on my goal of remaining the best.', 'active'),
('Max', 'Holloway', 'mholloway@ufc.com', '012345 678912', 'In love with the sport, always striving to improve and challenge myself with every fight.', 'active'),
('Stipe', 'Miocic', 'smiocic@ufc.com', '012345 678913', 'Ready to make history, determined to defend my heavyweight title and prove my dominance.', 'active'),
('Daniel', 'Cormier', 'dcormier@ufc.com', '012345 678914', 'Two-time champ, still hungry, still working harder than anyone to achieve greatness.', 'active'),
('Frankie', 'Edgar', 'fedgar@ufc.com', '012345 678915', 'I’ve seen it all in the octagon, but I’m not done yet, still chasing that title.', 'active'),
('Demetrious', 'Johnson', 'djohnson@ufc.com', '012345 678916', 'Training with the best and always improving my craft, the best is yet to come.', 'active'),
('Gilbert', 'Burns', 'gburns@ufc.com', '012345 678917', 'Focused on the title, always pushing myself to be the best in the welterweight division.', 'active'),
('Brock', 'Lesnar', 'blesnar@ufc.com', '012345 678918', 'Comeback mode: On. I’m ready to take the heavyweight division by storm once again.', 'active'),
('Anthony', 'Pettis', 'apettis@ufc.com', '012345 678919', 'Time for a new challenge, I’ve conquered the lightweight division and I’m ready for more.', 'active'),
('Dominick', 'Cruz', 'dcruz@ufc.com', '012345 678920', 'Proud of my legacy, but still hungry for more. The bantamweight division isn’t done with me.', 'active'),
('Robert', 'Whittaker', 'rwhittaker@ufc.com', '012345 678921', 'Training for greatness, getting back to the top, and putting the middleweight division on notice.', 'active'),
('Jan', 'Blachowicz', 'jblachowicz@ufc.com', '012345 678922', 'No one beats me in my prime, I’ll defend this title with everything I’ve got.', 'active'),
('Paige', 'VanZant', 'pvanzant@ufc.com', '012345 678923', 'Aiming for the top! Every fight is an opportunity to prove I belong among the best.', 'active'),
('Michael', 'Chandler', 'mchandler@ufc.com', '012345 678924', 'Let’s bring the fireworks, always ready to give the fans what they want – explosive fights.', 'active'),
('Max', 'Holloway', 'mholloway@ufc.com', '012345 678961', 'Feeding my passion for victory, nothing will stand in my way of becoming the champion again.', 'active'),
('Stipe', 'Miocic', 'smiocic@ufc.com', '012345 678962', 'I’ll keep fighting for the heavyweight crown, no one is taking that away from me.', 'disabled'),
('Daniel', 'Cormier', 'dcormier@ufc.com', '012345 678963', 'Two-time champion, one more for the fans. I’m determined to give it my all until the very end.', 'active'),
('Frankie', 'Edgar', 'fedgar@ufc.com', '012345 678964', 'The journey isn’t over yet, I’ve got more left in the tank to reach the top one last time.', 'disabled'),
('Demetrious', 'Johnson', 'djohnson@ufc.com', '012345 678965', 'Fighting for the best legacy, always pushing the limits and chasing greatness.', 'active'),
('Gilbert', 'Burns', 'gburns@ufc.com', '012345 678966', 'Ready to take over the division, I’ve been putting in the work to become the best.', 'active'),
('Brock', 'Lesnar', 'blesnar@ufc.com', '012345 678967', 'Brock is back, let’s make it interesting. The heavyweight division is mine to conquer.', 'disabled'),
('Anthony', 'Pettis', 'apettis@ufc.com', '012345 678968', 'Still one of the best in the world, always ready for the next big challenge in my career.', 'active'),
('Charles', 'Oliveira', 'coliveira@ufc.com', '012345 678925', 'I’m the king of submissions, always looking for that perfect finish to prove my dominance.', 'active'),
('Miesha', 'Tate', 'mtate@ufc.com', '012345 678926', 'Time to reclaim the crown, I’ve learned a lot and I’m ready to show the world my true potential.', 'active'),
('T.J.', 'Dillashaw', 'tjdillashaw@ufc.com', '012345 678927', 'Focused on the championship, I will fight with everything I’ve got to reclaim what’s mine.', 'active'),
('Sean', 'O’Malley', 'somalley@ufc.com', '012345 678928', 'The future of MMA is here, and I’m going to make a statement with every fight.', 'active'),
('Chris', 'Weidman', 'cweidman@ufc.com', '012345 678929', 'I’m back and better than ever. My body and mind are sharper than ever before.', 'active'),
('Curtis', 'Blaydes', 'cblaydes@ufc.com', '012345 678930', 'Hard work pays off, I’m focused on becoming the best heavyweight in the world.', 'active'),
('Jared', 'Cannonier', 'jcannonier@ufc.com', '012345 678931', 'Only the strong survive, and I’m ready to show that I’m the toughest guy in the division.', 'active'),
('Greg', 'Hardy', 'ghardy@ufc.com', '012345 678932', 'Ready to show my skills and prove myself to be one of the best in the UFC.', 'active'),
('Beneil', 'Dariush', 'bdariush@ufc.com', '012345 678984', 'Climbing the ranks, one fight at a time. Focused on becoming a champion and proving my worth.', 'active'),
('Claudia', 'Gadelha', 'cgadelha@ufc.com', '012345 678985', 'Back on top, stronger than ever, determined to show the world my skills and passion for MMA.', 'disabled'),
('Johnny', 'Walker', 'jwalker@ufc.com', '012345 678986', 'The unpredictable fighter, always looking to surprise my opponents with something new and dangerous.', 'active'),
('Magomed', 'Ankalaev', 'mankalaev@ufc.com', '012345 678987', 'Undefeated and unstoppable, my goal is to dominate the light heavyweight division and earn a title shot.', 'active'),
('Paul', 'Felder', 'pfelder@ufc.com', '012345 678988', 'Fighting is my passion, and I’ll continue to put on thrilling performances for the fans.', 'disabled'),
('Jamahal', 'Hill', 'jhill@ufc.com', '012345 678989', 'Focused on getting to the top of the mountain, and nothing is going to stop me from reaching it.', 'active'),
('Tony', 'Ferguson', 'tferguson01@ufc.com', '012345 678990', 'Chaos is still alive, ready to put on a show and prove I’m still one of the best in the world.', 'disabled'),
('Marvin', 'Vettori', 'mvettori@ufc.com', '012345 678991', 'The middleweight division belongs to me. I’ll prove it in every fight I take.', 'active'),
('Islam', 'Makhachev', 'imakhachev@ufc.com', '012345 678992', 'Aiming for the lightweight throne, I will continue my undefeated streak until I get there.', 'active'),
('Leon', 'Edwards', 'ledwards@ufc.com', '012345 678993', 'I’m coming for the title, no one is stopping me from achieving my dreams.', 'active'),
('Zhang', 'Weili', 'zweili@ufc.com', '012345 678994', 'Champion mentality, always focused, and determined to defend my title in every fight.', 'active'),
('Cory', 'Sandhagen', 'csandhagen@ufc.com', '012345 678933', 'The division belongs to me, and I’m going to prove it by taking the title away from whoever stands in my way.', 'active'),
('Nick', 'Diaz', 'ndiaz01@ufc.com', '012345 678934', 'Can’t wait for the next war. I fight for the love of the sport and to show what real warriors do.', 'active'),
('Beneil', 'Dariush', 'bdariush@ufc.com', '012345 678935', 'Focused on the belt, I’ve earned my spot and I’m coming for it, no one will stand in my way.', 'active'),
('Dominick', 'Cruz', 'dcruz@ufc.com', '012345 678969', 'It’s all about the footwork, and I’ll keep showing that I’m the smartest fighter in the cage.', 'active'),
('Robert', 'Whittaker', 'rwhittaker@ufc.com', '012345 678970', 'Focused on getting back to the title, I’m constantly evolving to stay ahead of the competition.', 'active'),
('Jan', 'Blachowicz', 'jblachowicz@ufc.com', '012345 678971', 'You have to beat me to take the crown. I’m the most dangerous man in the division.', 'active'),
('Paige', 'VanZant', 'pvanzant@ufc.com', '012345 678972', 'Living my dream every day, but I’m also on a mission to take my place at the top of the division.', 'active'),
('Michael', 'Chandler', 'mchandler@ufc.com', '012345 678973', 'Let’s make some noise, I’ll bring the fireworks and show the world what a real fighter looks like.', 'active'),
('Charles', 'Oliveira', 'coliveira@ufc.com', '012345 678974', 'I’ll be remembered as the greatest submission artist to ever step foot in the octagon.', 'active'),
('Miesha', 'Tate', 'mtate@ufc.com', '012345 678975', 'Fighting for another title run. I’m not done yet, and I’ve got more to prove to the world.', 'active'),
('T.J.', 'Dillashaw', 'tjdillashaw@ufc.com', '012345 678976', 'A champion’s mentality, always prepared and ready to be the best in the division again.', 'active'),
('Sean', 'O’Malley', 'somalley@ufc.com', '012345 678977', 'The future of MMA, I’m ready to take over the sport and become the next big star in the UFC.', 'active'),
('Chris', 'Weidman', 'cweidman@ufc.com', '012345 678978', 'I’m still the champ in my mind, and I’m back to prove I can still compete at the highest level.', 'disabled'),
('Curtis', 'Blaydes', 'cblaydes@ufc.com', '012345 678979', 'The heavyweights are my division, and I’ll dominate until I take the belt around my waist.', 'active'),
('Jared', 'Cannonier', 'jcannonier@ufc.com', '012345 678980', 'The title is within my reach. Every fight I take, I get closer to being a champion.', 'active'),
('Greg', 'Hardy', 'ghardy@ufc.com', '012345 678981', 'Ready to show my skills in the cage, and I’m here to make a statement with every fight I take.', 'active'),
('Cory', 'Sandhagen', 'csandhagen@ufc.com', '012345 678982', 'The title is closer every day, I’m ready to show the world that I am the next bantamweight king.', 'disabled'),
('Nick', 'Diaz', 'ndiaz01@ufc.com', '012345 678983', 'Don’t ever count me out. I’ve been through it all and I’m ready to get back to my best.', 'disabled'),
('Claudia', 'Gadelha', 'cgadelha@ufc.com', '012345 678936', 'In the gym every day, working hard to earn my spot at the top of the strawweight division.', 'active'),
('Johnny', 'Walker', 'jwalker@ufc.com', '012345 678937', 'Flipping the game upside down, every time I step into the octagon, I’m bringing chaos and unpredictability.', 'active'),
('Magomed', 'Ankalaev', 'mankalaev@ufc.com', '012345 678938', 'Undefeated and unstoppable, I’m here to show the world that I am the future of the light heavyweight division.', 'active'),
('Paul', 'Felder', 'pfelder@ufc.com', '012345 678939', 'Fighting is in my blood, and I’m going to continue proving that I’m one of the best in the world.', 'active'),
('Jamahal', 'Hill', 'jhill@ufc.com', '012345 678940', 'Aiming for the top of the mountain, I’ve got my eyes set on the light heavyweight title and nothing will stop me.', 'active'),
('Tony', 'Ferguson', 'tferguson01@ufc.com', '012345 678941', 'Time to bring chaos back to the cage. I’ll show the world what true unpredictability looks like in action.', 'active'),
('Marvin', 'Vettori', 'mvettori@ufc.com', '012345 678942', 'I’m always in the fight, never backing down from any challenge that comes my way in the middleweight division.', 'active'),
('Islam', 'Makhachev', 'imakhachev@ufc.com', '012345 678943', 'Strength is my weapon, and I’ll keep proving that I’m the future of the lightweight division.', 'active'),
('Leon', 'Edwards', 'ledwards@ufc.com', '012345 678944', 'The title is coming home to me, no one will stand in my way as I move closer to my ultimate goal.', 'active'),
('Zhang', 'Weili', 'zweili@ufc.com', '012345 678945', 'I am the queen of this division, and I’ll defend my crown with everything I’ve got.', 'active'),
('Kaitlyn', 'Chookagian', 'kchookagian@ufc.com', '012345 678946', 'All about hard work and dedication. I’m here to prove that I’m one of the best in the flyweight division.', 'active'),
('Tatiana', 'Suarez', 'tsuarez@ufc.com', '012345 678947', 'Ready to dominate, every step I take brings me closer to becoming the most dangerous woman in MMA.', 'active'),
('Angela', 'Hill', 'ahill@ufc.com', '012345 678948', 'On a mission to be the best, I’m focused on climbing the ranks to earn my title shot and prove myself.', 'active'),
('Aspen', 'Ladd', 'aladd@ufc.com', '012345 678949', 'Aiming for the top one fight at a time, I’m relentless in my pursuit of greatness.', 'active'),
('Lauren', 'Murphy', 'lmurphy@ufc.com', '012345 678950', 'Hard work and perseverance are key. I’m putting everything I have into reaching the top of my division.', 'active'),
('Andrea', 'Lee', 'alee@ufc.com', '012345 678951', 'Focused on my next win, every fight brings me closer to the top.', 'active'),
('Kaitlyn', 'Chookagian', 'kchookagian@ufc.com', '012345 678995', 'Just getting started, I’m ready to prove that I’m a force to be reckoned with in the flyweight division.', 'disabled'),
('Tatiana', 'Suarez', 'tsuarez@ufc.com', '012345 678996', 'Determined to be the best, my journey is just beginning and I’m not stopping until I reach the top.', 'active'),
('Angela', 'Hill', 'ahill@ufc.com', '012345 678997', 'On my way to the title, every fight is a step closer to the gold.', 'active'),
('Aspen', 'Ladd', 'aladd@ufc.com', '012345 678998', 'Nothing can stop me now, I’ve got my eyes set on the top and I’m going to make it happen.', 'disabled'),
('Lauren', 'Murphy', 'lmurphy@ufc.com', '012345 678999', 'Fighting to be the best in the world, I’m willing to do whatever it takes to get there.', 'active'),
('Andrea', 'Lee', 'alee@ufc.com', '012345 679000', 'I’m always improving, every fight helps me grow stronger and more prepared for the championship.', 'disabled'),
('Jessica', 'Andrade', 'jandrade@ufc.com', '012345 679001', 'Ready to make my comeback and prove that I’m still one of the most dangerous fighters in the world.', 'active'),
('Rose', 'Namajunas', 'rnamajunas01@ufc.com', '012345 679002', 'Focused on getting my title back, nothing will stand in my way on this journey.', 'active'),
('Raquel', 'Pennington', 'rpennington@ufc.com', '012345 679003', 'I’m coming for the top spot, I’ve got the skills and mentality to take over the division.', 'disabled'),
('Yana', 'Kunitskaya', 'ykunitskaya@ufc.com', '012345 679004', 'I won’t stop until I’m champion, my determination and hard work will take me to the top.', 'active'),
('Amanda', 'Lemos', 'alemos@ufc.com', '012345 679005', 'The title is in my sights, every fight brings me closer to making that dream a reality.', 'active'),
('Juliana', 'Pena', 'jpena@ufc.com', '012345 679006', 'Get ready for the next champion, my time to shine is coming soon and I won’t waste it.', 'active'),
('Cynthia', 'Calvillo', 'ccalvillo@ufc.com', '012345 679007', 'Determined to fight for the belt, every fight is a step toward that championship gold.', 'active'),
('Karolina', 'Kowalkiewicz', 'kkowalkiewicz@ufc.com', '012345 679008', 'The comeback is real, I’m here to show the world that I’m still a top contender in the division.', 'active'),
('Felice', 'Herrig', 'fherrig@ufc.com', '012345 679009', 'Fighting for my dream every day, my journey to the top is just beginning and I won’t give up.', 'active'),
('Jessica', 'Andrade', 'jandrade@ufc.com', '012345 678952', 'No one can stop me now, I’ve never been more focused and determined to take back my title.', 'active'),
('Rose', 'Namajunas', 'rnamajunas01@ufc.com', '012345 678953', 'I’ll be the champion again, my heart and mind are stronger than ever, and I won’t stop until I’m on top again.', 'active'),
('Raquel', 'Pennington', 'rpennington@ufc.com', '012345 678954', 'I’ll rise again, my skills are sharper, and my focus is on winning the belt and becoming a champion.', 'active'),
('Yana', 'Kunitskaya', 'ykunitskaya@ufc.com', '012345 678955', 'Getting better every day, I’ve got the drive and determination to be the best in my weight class.', 'active'),
('Amanda', 'Lemos', 'alemos@ufc.com', '012345 678956', 'Always working hard for the next opportunity, the title is my goal and I won’t stop until it’s mine.', 'active'),
('Juliana', 'Pena', 'jpena@ufc.com', '012345 678957', 'Ready for my next challenge, I’ll show the world why I’m one of the best in the division and earn that belt.', 'active'),
('Cynthia', 'Calvillo', 'ccalvillo@ufc.com', '012345 678958', 'On a mission to be the best, my focus is sharp and I’ll prove to the world that I belong at the top.', 'active'),
('Karolina', 'Kowalkiewicz', 'kkowalkiewicz@ufc.com', '012345 678959', 'I’ve got the heart to win, and I’ll prove it in every fight I take until I earn my spot as champion.', 'active'),
('Felice', 'Herrig', 'fherrig@ufc.com', '012345 678960', 'Fighting for my dream, I won’t stop until I’m at the top of the division, ready to claim my title.', 'active'),
('Jessica', 'Andrade', 'jandrade@ufc.com', '012345 678961', 'I’ve got the power, skill, and heart to become the champion again, and I’m going to make it happen.', 'active'),
('Rose', 'Namajunas', 'rnamajunas01@ufc.com', '012345 678962', 'I’ve been through it all, and I’m coming back stronger than ever to take the title again.', 'active'),
('Raquel', 'Pennington', 'rpennington@ufc.com', '012345 678963', 'Focused on rising to the top, I’m more determined than ever to show that I’m a force to be reckoned with.', 'active'),
('Yana', 'Kunitskaya', 'ykunitskaya@ufc.com', '012345 678964', 'The road to the title is long, but I’m willing to put in the work and fight through anything to get there.', 'active'),
('Amanda', 'Lemos', 'alemos@ufc.com', '012345 678965', 'Focused on my next big challenge, I won’t stop until I hold that championship belt in my hands.', 'active'),
('Juliana', 'Pena', 'jpena@ufc.com', '012345 678966', 'The next champion is here, and I’m ready to prove myself in every fight until I claim my rightful spot at the top.', 'active'),
('Claudia', 'Gadelha', 'cgadelha@ufc.com', '012345 679010', 'Focused on reclaiming my spot at the top of the division, every day is a step closer.', 'active'),
('Johnny', 'Walker', 'jwalker@ufc.com', '012345 679011', 'Flipping the game upside down, my unpredictable style will keep opponents guessing.', 'active'),
('Magomed', 'Ankalaev', 'mankalaev@ufc.com', '012345 679012', 'Undefeated and unstoppable, my reign is just beginning and I’m ready for anything.', 'active'),
('Paul', 'Felder', 'pfelder@ufc.com', '012345 679013', 'Fighting is in my blood, and I’ll show the world that I’m one of the best in the sport.', 'active'),
('Jamahal', 'Hill', 'jhill@ufc.com', '012345 679014', 'Aiming for the top of the mountain, I’m not stopping until I reach the peak of this sport.', 'active'),
('Tony', 'Ferguson', 'tferguson01@ufc.com', '012345 679015', 'Time to bring chaos back to the cage, I’m ready to make my mark once again.', 'active'),
('Marvin', 'Vettori', 'mvettori@ufc.com', '012345 679016', 'I’m always in the fight, every challenge makes me stronger and more focused on my goals.', 'active'),
('Islam', 'Makhachev', 'imakhachev@ufc.com', '012345 679017', 'Strength is my weapon, and my determination will carry me to the lightweight title.', 'active'),
('Leon', 'Edwards', 'ledwards@ufc.com', '012345 679018', 'The title is coming home to me, I’m ready to show that I’m the best in the world.', 'active'),
('Zhang', 'Weili', 'zweili@ufc.com', '012345 679019', 'I am the queen of this division, my reign is just beginning and no one can stop me.', 'active'),
('Kaitlyn', 'Chookagian', 'kchookagian@ufc.com', '012345 679020', 'All about hard work and dedication, I’ve got the mentality to dominate and keep pushing for greatness.', 'active'),
('Tatiana', 'Suarez', 'tsuarez@ufc.com', '012345 679021', 'Ready to dominate, I’ve been through the grind and now it’s time to make my mark on the sport.', 'active'),
('Angela', 'Hill', 'ahill@ufc.com', '012345 679022', 'On a mission to be the best, my focus is on winning every fight and proving that I belong at the top.', 'active'),
('Aspen', 'Ladd', 'aladd@ufc.com', '012345 679023', 'Aiming for the top one fight at a time, I’m ready to show the world what I’m made of.', 'active'),
('Lauren', 'Murphy', 'lmurphy@ufc.com', '012345 679024', 'Hard work and perseverance are key, every day is an opportunity to improve and get closer to my goal.', 'active'),
('Andrea', 'Lee', 'alee@ufc.com', '012345 679025', 'Focused on my next win, I’m sharpening my skills and making sure every fight counts toward my future success.', 'active'),
('Kaitlyn', 'Chookagian', 'kchookagian@ufc.com', '012345 679026', 'Just getting started, I have the determination and work ethic to be the best in this division.', 'active'),
('Tatiana', 'Suarez', 'tsuarez@ufc.com', '012345 679027', 'Determined to be the best, I’m focused on taking over the flyweight division and making history.', 'active'),
('Angela', 'Hill', 'ahill@ufc.com', '012345 679028', 'On my way to the title, I’ll prove I’m ready for the big stage and claim my place among the greatest.', 'active'),
('Aspen', 'Ladd', 'aladd@ufc.com', '012345 679029', 'Nothing can stop me now, I’m working hard to prove that I have what it takes to be a champion.', 'active'),
('Lauren', 'Murphy', 'lmurphy@ufc.com', '012345 679030', 'Focused on climbing the ranks, every fight gets me closer to reaching my ultimate goal of becoming champion.', 'active'),
('Andrea', 'Lee', 'alee@ufc.com', '012345 679031', 'Focused on improving with every fight, each step brings me closer to achieving my dreams.', 'active'),
('Jessica', 'Andrade', 'jandrade@ufc.com', '012345 679032', 'I’ve learned from every setback and now I’m ready to come back stronger than ever, no one can stop me.', 'active'),
('Rose', 'Namajunas', 'rnamajunas01@ufc.com', '012345 679033', 'Focused on reclaiming my title, I’m more prepared than ever to prove I’m the best in the world.', 'active'),
('Raquel', 'Pennington', 'rpennington@ufc.com', '012345 679034', 'Ready to rise to the top, my determination and focus will take me there and beyond.', 'active'),
('Yana', 'Kunitskaya', 'ykunitskaya@ufc.com', '012345 679035', 'I won’t stop until I’m champion, every fight is a step toward making my dream a reality.', 'active'),
('Amanda', 'Lemos', 'alemos@ufc.com', '012345 679036', 'The title is in my sights, every day I get one step closer to making that dream come true.', 'active'),
('Juliana', 'Pena', 'jpena@ufc.com', '012345 679037', 'The next champion is here, ready to rise to the occasion and make my mark in the UFC.', 'active'),
('Cynthia', 'Calvillo', 'ccalvillo@ufc.com', '012345 679038', 'Determined to fight for the belt, my journey to the top will be marked by hard work and grit.', 'active'),
('Karolina', 'Kowalkiewicz', 'kkowalkiewicz@ufc.com', '012345 679039', 'The comeback is real, I’m focused and determined to show I’m still one of the top fighters in the division.', 'active');

