USE usermgt;

CREATE TABLE `usermgt`.`user`
(
   `id`         INT NOT NULL auto_increment,
   `first_name` VARCHAR(45) NOT NULL,
   `last_name`  VARCHAR(45) NOT NULL,
   `email`      VARCHAR(45) NOT NULL,
   `phone`      VARCHAR(45) NOT NULL,
   `comments`   TEXT NOT NULL,
   `status`     VARCHAR(10) NOT NULL DEFAULT 'active',
   PRIMARY KEY (`id`)
)
engine = innodb;

INSERT INTO `user`
            (`id`,
             `first_name`,
             `last_name`,
             `email`,
             `phone`,
             `comments`,
             `status`)
VALUES      (NULL,
             'Amanda',
             'Nunes',
             'anunes@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Alexander',
             'Volkanovski',
             'avolkanovski@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Khabib',
             'Nurmagomedov',
             'knurmagomedov@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Kamaru',
             'Usman',
             'kusman@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Israel',
             'Adesanya',
             'iadesanya@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Henry',
             'Cejudo',
             'hcejudo@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Valentina',
             'Shevchenko',
             'vshevchenko@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Tyron',
             'Woodley',
             'twoodley@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Rose',
             'Namajunas',
             'rnamajunas@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Tony',
             'Ferguson',
             'tferguson@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Jorge',
             'Masvidal',
             'jmasvidal@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Nate',
             'Diaz',
             'ndiaz@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Conor',
             'McGregor',
             'cmcGregor@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Cris',
             'Cyborg',
             'ccyborg@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Tecia',
             'Torres',
             'ttorres@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Ronda',
             'Rousey',
             'rrousey@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Holly',
             'Holm',
             'hholm@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active'),
            (NULL,
             'Joanna',
             'Jedrzejczyk',
             'jjedrzejczyk@ufc.com',
             '012345 678910',
             'I Love VPS',
             'active');
